# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: trusty
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

notifications:
  email:
    recipients:
      - 130s@2000.jukuin.keio.ac.jp
env:
  global:
    - ROS_DISTRO=melodic
    - ROS_REPO=ros
    - UPSTREAM_WORKSPACE=moveit.rosinstall
    - TEST_BLACKLIST=moveit_ros_perception  # mesh_filter_test fails due to broken Mesa OpenGL
  matrix:
    - TEST=clang-format
    - ROS_DISTRO=melodic
    - ROS_DISTRO=kinetic

matrix: # Add a separate config to the matrix, using clang as compiler
  include:
    # add a config to the matrix using clang as compiler and also test ikfast plugin creation
    - compiler: clang
      env: ROS_REPO=ros-shadow-fixed
           BEFORE_DOCKER_SCRIPT="source moveit_kinematics/test/test_ikfast_plugins.sh"

before_script:
  - git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci

script:
  - .moveit_ci/travis.sh
